/** Export utilities for CSV and print. */

export function exportToCSV(data: Record<string, unknown>[], filename: string) {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(','),
    ...data.map((row) =>
      headers
        .map((header) => {
          const value = row[header];
          if (value === null || value === undefined) return '';
          const str = String(value).replace(/"/g, '""');
          return `"${str}"`;
        })
        .join(','),
    ),
  ];

  const csv = csvRows.join('\n');
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename.endsWith('.csv') ? filename : `${filename}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

export function printHTML(html: string, title: string) {
  const printWindow = window.open('', '_blank', 'width=800,height=600');
  if (!printWindow) {
    alert('Please allow popups to print');
    return;
  }
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: 'Inter', system-ui, sans-serif; margin: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
        th { background: #f4f6f9; font-weight: 600; }
        h1 { font-size: 18px; }
        .header { margin-bottom: 20px; }
        .footer { margin-top: 20px; text-align: center; font-size: 10px; color: #999; }
        @media print {
          body { margin: 0; }
        }
      </style>
    </head>
    <body>
      ${html}
      <div class="footer">Generated by BARIS on ${new Date().toLocaleString('en-PH')}</div>
    </body>
    </html>
  `);
  printWindow.document.close();
  setTimeout(() => {
    printWindow.print();
  }, 300);
}

export function exportTablePDF(
  title: string,
  subtitle: string,
  columns: { key: string; label: string }[],
  rows: Record<string, unknown>[],
) {
  const tableHtml = `
    <div class="header">
      <h1>${title}</h1>
      <p>${subtitle}</p>
      <p>Total records: ${rows.length}</p>
    </div>
    <table>
      <thead>
        <tr>${columns.map((c) => `<th>${c.label}</th>`).join('')}</tr>
      </thead>
      <tbody>
        ${rows
          .map(
            (row) =>
              `<tr>${columns.map((c) => `<td>${row[c.key] ?? ''}</td>`).join('')}</tr>`,
          )
          .join('')}
      </tbody>
    </table>
  `;
  printHTML(tableHtml, title);
}
